/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRepositoriesRouteImport } from './routes/api/repositories'
import { Route as ApiFileContentRouteImport } from './routes/api/file-content'
import { Route as ApiDiffRouteImport } from './routes/api/diff'
import { Route as ApiCurrentBranchRouteImport } from './routes/api/current-branch'
import { Route as ApiCommitsRouteImport } from './routes/api/commits'
import { Route as ApiCommitDistanceRouteImport } from './routes/api/commit-distance'
import { Route as ApiBranchesWithCommitsRouteImport } from './routes/api/branches-with-commits'
import { Route as ApiBranchesRouteImport } from './routes/api/branches'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepositoriesRoute = ApiRepositoriesRouteImport.update({
  id: '/api/repositories',
  path: '/api/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileContentRoute = ApiFileContentRouteImport.update({
  id: '/api/file-content',
  path: '/api/file-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiffRoute = ApiDiffRouteImport.update({
  id: '/api/diff',
  path: '/api/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurrentBranchRoute = ApiCurrentBranchRouteImport.update({
  id: '/api/current-branch',
  path: '/api/current-branch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommitsRoute = ApiCommitsRouteImport.update({
  id: '/api/commits',
  path: '/api/commits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommitDistanceRoute = ApiCommitDistanceRouteImport.update({
  id: '/api/commit-distance',
  path: '/api/commit-distance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBranchesWithCommitsRoute = ApiBranchesWithCommitsRouteImport.update({
  id: '/api/branches-with-commits',
  path: '/api/branches-with-commits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBranchesRoute = ApiBranchesRouteImport.update({
  id: '/api/branches',
  path: '/api/branches',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/branches': typeof ApiBranchesRoute
  '/api/branches-with-commits': typeof ApiBranchesWithCommitsRoute
  '/api/commit-distance': typeof ApiCommitDistanceRoute
  '/api/commits': typeof ApiCommitsRoute
  '/api/current-branch': typeof ApiCurrentBranchRoute
  '/api/diff': typeof ApiDiffRoute
  '/api/file-content': typeof ApiFileContentRoute
  '/api/repositories': typeof ApiRepositoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/branches': typeof ApiBranchesRoute
  '/api/branches-with-commits': typeof ApiBranchesWithCommitsRoute
  '/api/commit-distance': typeof ApiCommitDistanceRoute
  '/api/commits': typeof ApiCommitsRoute
  '/api/current-branch': typeof ApiCurrentBranchRoute
  '/api/diff': typeof ApiDiffRoute
  '/api/file-content': typeof ApiFileContentRoute
  '/api/repositories': typeof ApiRepositoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/branches': typeof ApiBranchesRoute
  '/api/branches-with-commits': typeof ApiBranchesWithCommitsRoute
  '/api/commit-distance': typeof ApiCommitDistanceRoute
  '/api/commits': typeof ApiCommitsRoute
  '/api/current-branch': typeof ApiCurrentBranchRoute
  '/api/diff': typeof ApiDiffRoute
  '/api/file-content': typeof ApiFileContentRoute
  '/api/repositories': typeof ApiRepositoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/branches'
    | '/api/branches-with-commits'
    | '/api/commit-distance'
    | '/api/commits'
    | '/api/current-branch'
    | '/api/diff'
    | '/api/file-content'
    | '/api/repositories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/branches'
    | '/api/branches-with-commits'
    | '/api/commit-distance'
    | '/api/commits'
    | '/api/current-branch'
    | '/api/diff'
    | '/api/file-content'
    | '/api/repositories'
  id:
    | '__root__'
    | '/'
    | '/api/branches'
    | '/api/branches-with-commits'
    | '/api/commit-distance'
    | '/api/commits'
    | '/api/current-branch'
    | '/api/diff'
    | '/api/file-content'
    | '/api/repositories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBranchesRoute: typeof ApiBranchesRoute
  ApiBranchesWithCommitsRoute: typeof ApiBranchesWithCommitsRoute
  ApiCommitDistanceRoute: typeof ApiCommitDistanceRoute
  ApiCommitsRoute: typeof ApiCommitsRoute
  ApiCurrentBranchRoute: typeof ApiCurrentBranchRoute
  ApiDiffRoute: typeof ApiDiffRoute
  ApiFileContentRoute: typeof ApiFileContentRoute
  ApiRepositoriesRoute: typeof ApiRepositoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repositories': {
      id: '/api/repositories'
      path: '/api/repositories'
      fullPath: '/api/repositories'
      preLoaderRoute: typeof ApiRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-content': {
      id: '/api/file-content'
      path: '/api/file-content'
      fullPath: '/api/file-content'
      preLoaderRoute: typeof ApiFileContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diff': {
      id: '/api/diff'
      path: '/api/diff'
      fullPath: '/api/diff'
      preLoaderRoute: typeof ApiDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/current-branch': {
      id: '/api/current-branch'
      path: '/api/current-branch'
      fullPath: '/api/current-branch'
      preLoaderRoute: typeof ApiCurrentBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commits': {
      id: '/api/commits'
      path: '/api/commits'
      fullPath: '/api/commits'
      preLoaderRoute: typeof ApiCommitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commit-distance': {
      id: '/api/commit-distance'
      path: '/api/commit-distance'
      fullPath: '/api/commit-distance'
      preLoaderRoute: typeof ApiCommitDistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/branches-with-commits': {
      id: '/api/branches-with-commits'
      path: '/api/branches-with-commits'
      fullPath: '/api/branches-with-commits'
      preLoaderRoute: typeof ApiBranchesWithCommitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/branches': {
      id: '/api/branches'
      path: '/api/branches'
      fullPath: '/api/branches'
      preLoaderRoute: typeof ApiBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBranchesRoute: ApiBranchesRoute,
  ApiBranchesWithCommitsRoute: ApiBranchesWithCommitsRoute,
  ApiCommitDistanceRoute: ApiCommitDistanceRoute,
  ApiCommitsRoute: ApiCommitsRoute,
  ApiCurrentBranchRoute: ApiCurrentBranchRoute,
  ApiDiffRoute: ApiDiffRoute,
  ApiFileContentRoute: ApiFileContentRoute,
  ApiRepositoriesRoute: ApiRepositoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
