/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDiffRouteImport } from './routes/api/diff'
import { Route as ApiCurrentBranchRouteImport } from './routes/api/current-branch'
import { Route as ApiCommitsRouteImport } from './routes/api/commits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiffRoute = ApiDiffRouteImport.update({
  id: '/api/diff',
  path: '/api/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurrentBranchRoute = ApiCurrentBranchRouteImport.update({
  id: '/api/current-branch',
  path: '/api/current-branch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommitsRoute = ApiCommitsRouteImport.update({
  id: '/api/commits',
  path: '/api/commits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/commits': typeof ApiCommitsRoute
  '/api/current-branch': typeof ApiCurrentBranchRoute
  '/api/diff': typeof ApiDiffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/commits': typeof ApiCommitsRoute
  '/api/current-branch': typeof ApiCurrentBranchRoute
  '/api/diff': typeof ApiDiffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/commits': typeof ApiCommitsRoute
  '/api/current-branch': typeof ApiCurrentBranchRoute
  '/api/diff': typeof ApiDiffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/commits' | '/api/current-branch' | '/api/diff'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/commits' | '/api/current-branch' | '/api/diff'
  id: '__root__' | '/' | '/api/commits' | '/api/current-branch' | '/api/diff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCommitsRoute: typeof ApiCommitsRoute
  ApiCurrentBranchRoute: typeof ApiCurrentBranchRoute
  ApiDiffRoute: typeof ApiDiffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diff': {
      id: '/api/diff'
      path: '/api/diff'
      fullPath: '/api/diff'
      preLoaderRoute: typeof ApiDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/current-branch': {
      id: '/api/current-branch'
      path: '/api/current-branch'
      fullPath: '/api/current-branch'
      preLoaderRoute: typeof ApiCurrentBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commits': {
      id: '/api/commits'
      path: '/api/commits'
      fullPath: '/api/commits'
      preLoaderRoute: typeof ApiCommitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCommitsRoute: ApiCommitsRoute,
  ApiCurrentBranchRoute: ApiCurrentBranchRoute,
  ApiDiffRoute: ApiDiffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
